repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.0
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format -i
        args: ["-style=file"]
        files: \.(c|cc|cpp|cxx|h|hh|hpp|hxx|ixx|inl)$
